[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "3.9"

[build]
builder = "gcr.io/buildpacks/builder:v1"

[[build.buildpacks]]
id = "google.python.runtime"

[[build.buildpacks]]
id = "google.python.pip"

[[build.buildpacks]]
id = "google.python.webserver"