name: Auto Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: probable-axon-451311-e1
  SERVICE: frequency-bot
  REGION: asia-east1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Deploy
      run: |
        gcloud run deploy ${{ env.SERVICE }} \
          --source . \
          --region ${{ env.REGION }} \
          --project ${{ env.PROJECT_ID }} \
          --allow-unauthenticated \
          --quiet

    - name: Verify Deployment
      run: |
        echo "Waiting for service to be ready..."
        sleep 10
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE }} --region ${{ env.REGION }} --format 'value(status.url)')
        echo "Service URL: $SERVICE_URL"
        
        # Check health endpoint
        HEALTH_STATUS=$(curl -s $SERVICE_URL/health | jq -r '.status')
        if [ "$HEALTH_STATUS" = "healthy" ]; then
          echo "✅ Deployment successful! Service is healthy."
        else
          echo "⚠️ Service deployed but health check failed."
          exit 1
        fi